"""Explicit research scopes and provenance-aware memory.

Revision ID: 0003
Revises: 0002
"""

import sqlalchemy as sa

from alembic import op

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clinical_memory_scopes",
        sa.Column("research_id", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clinical_memory_scopes")),
        sa.UniqueConstraint("research_id", name=op.f("uq_clinical_memory_scopes_research_id")),
    )
    op.create_table(
        "memory_episodes",
        sa.Column("scope_id", sa.Uuid(), nullable=False),
        sa.Column("clinical_case_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["clinical_case_id"],
            ["clinical_cases.id"],
            name=op.f("fk_memory_episodes_clinical_case_id_clinical_cases"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["scope_id"],
            ["clinical_memory_scopes.id"],
            name=op.f("fk_memory_episodes_scope_id_clinical_memory_scopes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory_episodes")),
        sa.UniqueConstraint("clinical_case_id", name=op.f("uq_memory_episodes_clinical_case_id")),
        sa.UniqueConstraint(
            "scope_id", "clinical_case_id", name=op.f("uq_memory_episodes_scope_id")
        ),
    )
    op.create_index(
        op.f("ix_memory_episodes_scope_id"), "memory_episodes", ["scope_id"], unique=False
    )
    op.create_table(
        "memory_entries",
        sa.Column("scope_id", sa.Uuid(), nullable=False),
        sa.Column("clinical_case_id", sa.Uuid(), nullable=False),
        sa.Column("entry_type", sa.String(length=32), nullable=False),
        sa.Column("source_record_id", sa.Uuid(), nullable=True),
        sa.Column("source_kind", sa.String(length=32), nullable=True),
        sa.Column("source_field", sa.String(length=64), nullable=True),
        sa.Column("producing_run_id", sa.Uuid(), nullable=True),
        sa.Column("producing_role", sa.String(length=128), nullable=True),
        sa.Column("snapshot", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("snapshot_digest", sa.String(length=71), nullable=False),
        sa.Column("identity_digest", sa.String(length=71), nullable=False),
        sa.Column("event", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(entry_type = 'source_fact' AND source_record_id IS NOT NULL AND "
            "source_kind IS NOT NULL AND source_field IS NOT NULL AND producing_run_id "
            "IS NULL) OR (entry_type = 'derived_assertion' AND producing_run_id IS NOT "
            "NULL AND source_record_id IS NULL AND source_kind IS NULL AND source_field "
            "IS NULL)",
            name=op.f("ck_memory_entries_origin_required"),
        ),
        sa.CheckConstraint(
            "entry_type IN ('source_fact', 'derived_assertion')",
            name=op.f("ck_memory_entries_entry_type_values"),
        ),
        sa.CheckConstraint(
            "source_kind IS NULL OR source_kind IN ('clinical_case', 'patient_profile', "
            "'condition', 'observation', 'medication', 'allergy', 'clinical_note')",
            name=op.f("ck_memory_entries_source_kind_values"),
        ),
        sa.ForeignKeyConstraint(
            ["producing_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_memory_entries_producing_run_id_agent_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["scope_id", "clinical_case_id"],
            ["memory_episodes.scope_id", "memory_episodes.clinical_case_id"],
            name=op.f("fk_memory_entries_scope_id_memory_episodes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["scope_id"],
            ["clinical_memory_scopes.id"],
            name=op.f("fk_memory_entries_scope_id_clinical_memory_scopes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory_entries")),
        sa.UniqueConstraint("scope_id", "identity_digest", name=op.f("uq_memory_entries_scope_id")),
    )
    op.create_index(
        op.f("ix_memory_entries_available_at"), "memory_entries", ["available_at"], unique=False
    )
    op.create_index(
        op.f("ix_memory_entries_clinical_case_id"),
        "memory_entries",
        ["clinical_case_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memory_entries_producing_run_id"),
        "memory_entries",
        ["producing_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memory_entries_scope_id"), "memory_entries", ["scope_id"], unique=False
    )
    op.create_table(
        "memory_evidence",
        sa.Column("entry_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_record_id", sa.Uuid(), nullable=False),
        sa.Column("identity_digest", sa.String(length=71), nullable=False),
        sa.Column("snapshot", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["memory_entries.id"],
            name=op.f("fk_memory_evidence_entry_id_memory_entries"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_record_id"],
            ["evidence_records.id"],
            name=op.f("fk_memory_evidence_evidence_record_id_evidence_records"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory_evidence")),
        sa.UniqueConstraint(
            "entry_id", "identity_digest", name=op.f("uq_memory_evidence_entry_id")
        ),
    )
    op.create_index(
        op.f("ix_memory_evidence_entry_id"), "memory_evidence", ["entry_id"], unique=False
    )
    op.create_index(
        op.f("ix_memory_evidence_evidence_record_id"),
        "memory_evidence",
        ["evidence_record_id"],
        unique=False,
    )
    op.create_table(
        "memory_relationships",
        sa.Column("scope_id", sa.Uuid(), nullable=False),
        sa.Column("from_entry_id", sa.Uuid(), nullable=False),
        sa.Column("to_entry_id", sa.Uuid(), nullable=False),
        sa.Column("relation_type", sa.String(length=32), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "relation_type IN ('supports', 'contradicts', 'supersedes', 'corrects')",
            name=op.f("ck_memory_relationships_relation_type_values"),
        ),
        sa.CheckConstraint(
            "from_entry_id <> to_entry_id", name=op.f("ck_memory_relationships_not_self")
        ),
        sa.ForeignKeyConstraint(
            ["from_entry_id"],
            ["memory_entries.id"],
            name=op.f("fk_memory_relationships_from_entry_id_memory_entries"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["scope_id"],
            ["clinical_memory_scopes.id"],
            name=op.f("fk_memory_relationships_scope_id_clinical_memory_scopes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["to_entry_id"],
            ["memory_entries.id"],
            name=op.f("fk_memory_relationships_to_entry_id_memory_entries"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory_relationships")),
        sa.UniqueConstraint(
            "from_entry_id",
            "to_entry_id",
            "relation_type",
            name=op.f("uq_memory_relationships_from_entry_id"),
        ),
    )
    op.create_index(
        op.f("ix_memory_relationships_from_entry_id"),
        "memory_relationships",
        ["from_entry_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memory_relationships_scope_id"), "memory_relationships", ["scope_id"], unique=False
    )
    op.create_index(
        op.f("ix_memory_relationships_to_entry_id"),
        "memory_relationships",
        ["to_entry_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_memory_relationships_to_entry_id"), table_name="memory_relationships")
    op.drop_index(op.f("ix_memory_relationships_scope_id"), table_name="memory_relationships")
    op.drop_index(op.f("ix_memory_relationships_from_entry_id"), table_name="memory_relationships")
    op.drop_table("memory_relationships")
    op.drop_index(op.f("ix_memory_evidence_evidence_record_id"), table_name="memory_evidence")
    op.drop_index(op.f("ix_memory_evidence_entry_id"), table_name="memory_evidence")
    op.drop_table("memory_evidence")
    op.drop_index(op.f("ix_memory_entries_scope_id"), table_name="memory_entries")
    op.drop_index(op.f("ix_memory_entries_producing_run_id"), table_name="memory_entries")
    op.drop_index(op.f("ix_memory_entries_clinical_case_id"), table_name="memory_entries")
    op.drop_index(op.f("ix_memory_entries_available_at"), table_name="memory_entries")
    op.drop_table("memory_entries")
    op.drop_index(op.f("ix_memory_episodes_scope_id"), table_name="memory_episodes")
    op.drop_table("memory_episodes")
    op.drop_table("clinical_memory_scopes")
    # ### end Alembic commands ###
